### ISSUE TITLE
3.0 and 3.1 crash when switching tags 

### ISSUE THREAD

**Issue by loverso** [mvglasow/satstat#103] opened 2016-10-25 18:12 UTC
I'm still running 2.2 on my 5.1 LGG4 because both the newer versions crash when I change from the

**Comment by licaon-kter** [comment] 2016-10-25 18:48
Logs?

**Comment by mvglasow** [comment] 2016-10-28 19:26
Closed as duplicate of #104

**Closed by mvglasow** 2016-10-28 19:26 UTC
Labels: duplicate
