### ISSUE TITLE
Null pointer error when going to maps

### ISSUE THREAD

**Issue by goldfndr** [mvglasow/satstat#107] opened 2016-11-21 08:19 UTC
When I try to go to a tab other than the main tab, the version 3.1 F-Droid binary of SatStat crashes ("Unfortunately, SatStat has stopped."), leaving the following log:

```
SatStat build: git-e7a0b8e


java.lang.NullPointerException
	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.showCellCdma(RadioSectionFragment.java:555)
	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.showCells(RadioSectionFragment.java:520)
	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.updateCellData(RadioSectionFragment.java:764)
	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.onCreateView(RadioSectionFragment.java:395)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:551)
	at android.support.design.widget.TabLayout$ViewPagerOnTabSelectedListener.onTabSelected(TabLayout.java:2008)
	at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1025)
	at android.support.design.widget.TabLayout.selectTab(TabLayout.java:995)
	at android.support.design.widget.TabLayout$Tab.select(TabLayout.java:1272)
	at android.support.design.widget.TabLayout$TabView.performClick(TabLayout.java:1377)
	at android.view.View$PerformClick.run(View.java:18465)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5086)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
```

My phone is a Motorola Moto G, KitKat 4.4.4, XT1028 (Verizon CDMA), admittedly with Xposed installed. Version 2,2 did not crash.

**Comment by goldfndr** [comment] 2017-02-15 09:05
Shouldn't this be marked as bug and #116 as duplicate?

**Comment by mvglasow** [comment] 2017-02-15 16:55
Sorry, I must have missed this one. This ticket is actually a duplicate of #104, which has already been fixed; just need to prepare a new release.

**Comment by mvglasow** [comment] 2017-09-11 22:58
Closing, as #104 is fixed by now.

**Closed by mvglasow** 2017-09-11 22:58 UTC
Labels: duplicate

**Comment by goldfndr** [comment] 2017-09-29 07:14
I hereby confirm that; with 3.2, crashing no longer occurs. Thanks!
