### ISSUE TITLE
Sateliteview: wrong timezone in "last fix" (german "letzte positionsbestimmung")

### ISSUE THREAD

**Issue by k3b** [mvglasow/satstat#45] opened 2015-04-15 04:52 UTC
This morning SatStat v2.0 (from f-droid) showed "letzte positionsbestimmung  5:39" (Last satelite fix)

My local time was 6:39 cest (central european summertime = utc + 2)

This is uk-local-summertime (utc+1) but neither utc (which has no summer timer) nor local time.

Is this a summertime issue?

**Comment by mvglasow** [comment] 2016-04-01 16:18
Hi and sorry for the delay! Fix time should be in local time, but I'm currently considering an option to choose between local time and UTC.

I can't reproduce your issue on my phone (neither during CET nor during CEST). I suspect it's something related to your device:

* Your device may have a faulty GPS implementation which delivers timestamps that are just plain wrong – I've seen that happen on some devices (and one of the reasons I wrote SatStat for is to find out such errors).
* Your device may be set to the wrong timezone but has its local time set so that it looks correct: For example, it may be 6:30 CEST (= 4:30 UTC) but your device is set to 6:30 BST (= 5:30 UTC). The time displayed by the clock looks right, but this is just an effect of two errors cancelling each other out. Any conversions between UTC and local time will be off by one hour.

**Comment by mvglasow** [comment] 2016-04-01 21:14
a494b53c adds an option to switch between UTC and local time. I'm planning to prepare a new release in the next few weeks which will include this functionality – try both options and see what time you get.

A faulty time zone config would introduce errors when selecting local time, but UTC should be OK. A botched GPS implementation would affect both UTC and local time in the same way.

**Comment by mvglasow** [comment] 2016-05-06 11:58
Version 2.1 has just been committed and should be available on F-Droid soon. That version will allow you to switch between UTC and local time for the time zone display. Let me know what time you see with each of these settings.

**Closed** 2017-09-23 13:53 UTC
Labels: awaiting feedback
