### ISSUE TITLE
Application crashes when clicking on "Settings"

### ISSUE THREAD

**Issue by mariyan-borisov** [mvglasow/satstat#89] opened 2016-07-19 20:53 UTC
Today I decided to upgrade from 2.2 to 3.0 and I wanted to see what's new. I clicked on "Settings" and the application crashed, then I decided to check where the bug is and fix it. The exception was the following:
> 07-19 19:45:06.229 1868-1868/com.vonglasow.michael.satstat E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vonglasow.michael.satstat/com.vonglasow.michael.satstat.SettingsActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class java.lang.reflect.Constructor
>                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
>                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
>                                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:141)
>                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
>                                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)
>                                                                                  at android.os.Looper.loop(Looper.java:137)
>                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5041)
>                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                                  at java.lang.reflect.Method.invoke(Method.java:511)
>                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
>                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
>                                                                                  at dalvik.system.NativeStart.main(Native Method)
>                                                                               Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class java.lang.reflect.Constructor
>                                                                                  at android.preference.GenericInflater.createItem(GenericInflater.java:397)
>                                                                                  at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430)
>                                                                                  at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
>                                                                                  at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
>                                                                                  at android.preference.GenericInflater.inflate(GenericInflater.java:326)
>                                                                                  at android.preference.GenericInflater.inflate(GenericInflater.java:263)
>                                                                                  at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:269)
>                                                                                  at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:285)
>                                                                                  at com.vonglasow.michael.satstat.SettingsActivity$SettingsFragment.onCreate(SettingsActivity.java:163)
>                                                                                  at android.app.Fragment.performCreate(Fragment.java:1677)
>                                                                                  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:854)
>                                                                                  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
>                                                                                  at android.app.BackStackRecord.run(BackStackRecord.java:682)
>                                                                                  at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
>                                                                                  at android.app.Activity.performStart(Activity.java:5113)
>                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
>                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
>                                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:141) 
>                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
>                                                                                  at android.os.Handler.dispatchMessage(Handler.java:99) 
>                                                                                  at android.os.Looper.loop(Looper.java:137) 
>                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5041) 
>                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                                  at java.lang.reflect.Method.invoke(Method.java:511) 
>                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
>                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
>                                                                                  at dalvik.system.NativeStart.main(Native Method) 
>                                                                               Caused by: java.lang.reflect.InvocationTargetException
>                                                                                  at java.lang.reflect.Constructor.constructNative(Native Method)
>                                                                                  at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
>                                                                                  at android.preference.GenericInflater.createItem(GenericInflater.java:383)
>                                                                                  at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430) 
>                                                                                  at android.preference.GenericInflater.rInflate(GenericInflater.java:481) 
>                                                                                  at android.preference.GenericInflater.rInflate(GenericInflater.java:493) 
>                                                                                  at android.preference.GenericInflater.inflate(GenericInflater.java:326) 
>                                                                                  at android.preference.GenericInflater.inflate(GenericInflater.java:263) 
>                                                                                  at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:269) 
>                                                                                  at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:285) 
>                                                                                  at com.vonglasow.michael.satstat.SettingsActivity$SettingsFragment.onCreate(SettingsActivity.java:163) 
>                                                                                  at android.app.Fragment.performCreate(Fragment.java:1677) 
>                                                                                  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:854) 
>                                                                                  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057) 
>                                                                                  at android.app.BackStackRecord.run(BackStackRecord.java:682) 
>                                                                                  at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435) 
>                                                                                  at android.app.Activity.performStart(Activity.java:5113) 
>                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153) 
>                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
>                                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:141) 
>                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
>                                                                                  at android.os.Handler.dispatchMessage(Handler.java:99) 
>                                                                                  at android.os.Looper.loop(Looper.java:137) 
>                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5041) 
>                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                                  at java.lang.reflect.Method.invoke(Method.java:511) 
>                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
>                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
>                                                                                  at dalvik.system.NativeStart.main(Native Method) 
>                                                                               Caused by: java.lang.NullPointerException
>                                                                                  at android.preference.MultiSelectListPreference.onGetDefaultValue(MultiSelectListPreference.java:212)
>                                                                                  at android.preference.Preference.<init>(Preference.java:267)
>                                                                                  at android.preference.DialogPreference.<init>(DialogPreference.java:69)
>                                                                                  at android.preference.DialogPreference.<init>(DialogPreference.java:90)
>                                                                                  at android.preference.MultiSelectListPreference.<init>(MultiSelectListPreference.java:49)
>                                                                                  at com.vonglasow.michael.satstat.widgets.LocProviderPreference.<init>(LocProviderPreference.java:22)
>                                                                                  at java.lang.reflect.Constructor.constructNative(Native Method) 
>                                                                                  at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
>                                                                                  at android.preference.GenericInflater.createItem(GenericInflater.java:383) 
>                                                                                  at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430) 
>                                                                                  at android.preference.GenericInflater.rInflate(GenericInflater.java:481) 
>                                                                                  at android.preference.GenericInflater.rInflate(GenericInflater.java:493) 
>                                                                                  at android.preference.GenericInflater.inflate(GenericInflater.java:326) 
>                                                                                  at android.preference.GenericInflater.inflate(GenericInflater.java:263) 
>                                                                                  at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:269) 
>                                                                                  at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:285) 
>                                                                                  at com.vonglasow.michael.satstat.SettingsActivity$SettingsFragment.onCreate(SettingsActivity.java:163) 
>                                                                                  at android.app.Fragment.performCreate(Fragment.java:1677) 
>                                                                                  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:854) 
>                                                                                  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057) 
>                                                                                  at android.app.BackStackRecord.run(BackStackRecord.java:682) 
>                                                                                  at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435) 
>                                                                                  at android.app.Activity.performStart(Activity.java:5113) 
>                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153) 
>                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
>                                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:141) 
>                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
>                                                                                  at android.os.Handler.dispatchMessage(Handler.java:99) 
>                                                                                  at android.os.Looper.loop(Looper.java:137) 
>                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5041) 
>                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                                  at java.lang.reflect.Method.invoke(Method.java:511) 
>                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
>                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
>                                                                                  at dalvik.system.NativeStart.main(Native Method)

I used git-bisect to find which commit introduced the bug and I found out it was this one https://github.com/mvglasow/satstat/commit/0cddd4a9a0b318f702d5f4dededf9f0c022a6740. Then I played with the code and I found which line caused the crash and it was this one https://github.com/mvglasow/satstat/blob/0cddd4a9a0b318f702d5f4dededf9f0c022a6740/res/xml/preferences.xml#L8. When I swap lines 7 and 8 the application no longer crashes and it can be used as a workaround. "ListPreference" can't be the last item in a "PreferenceCategory" for some unknown reason.
Tested with SDK versions 14, 17 and 23. The application doesn't crash when using version 23.

**Comment by mvglasow** [comment] 2016-07-19 21:58
Thanks for the analysis and patch! I'll look into it in more detail over the next days – it seems kind of strange that having a `ListPreference` as the last item of a `PreferenceCategory` should be the culprit (and only in conjunction with certain API levels). I have a suspicion that the true culprit is something else (I see a `NullPointerException` there, with a custom preference somewhere in the call stack), and reordering preferences might just be masquerading it.

When you tested it, did you upgrade over an existing version (without uninstalling first), or did you do a fresh install (including uninstall and reinstall) each time? In other words: did you start with "blank" preferences, or did you carry them over from a previous version?

**Comment by mariyan-borisov** [comment] 2016-07-19 22:17
> When you tested it, did you upgrade over an existing version (without uninstalling first), or did you do a fresh install (including uninstall and reinstall) each time?
I did a fresh install on my device (v17), then I tried it on another device (v14), then I tried it on an emulator (v17) and finally I tried it on a v23.
> I have a suspicion that the true culprit is something else (I see a NullPointerException there, with a custom preference somewhere in the call stack), and reordering preferences might just be masquerading it.
Yes, it could be. I also saw the NullPointerException and it seemed strange when it worked when I changed the order of the items.

**Comment by mvglasow** [comment] 2016-07-23 14:09
Just tested on my low-end device, which is API 19, and could not reproduce the crash, even after purging app data (as I suspected fresh app data might have to do with it)..

I'm directing my efforts at this part of the call stack:

> Caused by: java.lang.NullPointerException
> at android.preference.MultiSelectListPreference.onGetDefaultValue(MultiSelectListPreference.java:212)
> at android.preference.Preference.(Preference.java:267)
> at android.preference.DialogPreference.(DialogPreference.java:69)
> at android.preference.DialogPreference.(DialogPreference.java:90)
> at android.preference.MultiSelectListPreference.(MultiSelectListPreference.java:49)
> at com.vonglasow.michael.satstat.widgets.LocProviderPreference.(LocProviderPreference.java:22)

I came across [this post](http://stackoverflow.com/questions/17404549/multiselectlistpreference-error-inflating-class-java-lang-reflect-constructor/17404597#17404597) on StackOverflow, which describes similar symptoms, with a similar call stack, and an NPE getting thrown on API 22 but not on API 15. However, here it was related to setting a default value, whereas SatStat does not specify one.

**Comment by mvglasow** [comment] 2016-07-23 14:37
Managed to reproduce it on a virtual device running API 15. The first answer to the post did indeed have the answer: the trigger was the summary in XML. After removing the summary line, the Preference screen shows. That looks like an error in the widget library  which apparently got fixed in API 18 or 19. I'll look into setting the summary programmatically, as the post suggests.

**Comment by mariyan-borisov** [comment] 2016-07-23 15:47
Everything works now. Thanks!

**Closed** 2016-07-23 15:47 UTC
Labels: bug, resolved
