### ISSUE TITLE
App crashes, when clicking on settings menu

### ISSUE THREAD

**Issue by mst23** [mvglasow/satstat#93] opened 2016-07-27 19:09 UTC
Problem can be reproduced on:
* Sony Xperia M4 (Android 5.0)
* Asus MeMO Pad HD 7 ME173x (Android 4.2.2)

**Comment by mvglasow** [comment] 2016-07-28 19:11
Duplicate of #89, fixed in 3.1, which was made available on F-Droid today.

**Closed by mvglasow** 2016-07-28 19:11 UTC
Labels: duplicate
