### ISSUE TITLE
3.0 and 3.1 crash when switching tags 

### ISSUE THREAD

**Issue by loverso** [mvglasow/satstat#104] opened 2016-10-25 18:13 UTC
I'm still running 2.2 on my 5.1 LGG4 because both the newer versions crash when I change away from the main tab.

**Comment by licaon-kter** [comment] 2016-10-25 18:50
/duplicate of #103 
close this

**Comment by mvglasow** [comment] 2016-10-28 19:28
Can you pull a logcat right after the crash?

**Comment by loverso** [comment] 2016-10-29 13:20
I'm traveling but I will do so when I return.

**Comment by redcella** [comment] 2016-11-06 17:42
SatStat build: git-e7a0b8e


java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.showCellCdma(RadioSectionFragment.java:555)
	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.showCells(RadioSectionFragment.java:520)
	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.updateCellData(RadioSectionFragment.java:764)
	at com.vonglasow.michael.satstat.ui.RadioSectionFragment.onCreateView(RadioSectionFragment.java:395)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:551)
	at android.support.design.widget.TabLayout$ViewPagerOnTabSelectedListener.onTabSelected(TabLayout.java:2008)
	at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1025)
	at android.support.design.widget.TabLayout.selectTab(TabLayout.java:995)
	at android.support.design.widget.TabLayout$Tab.select(TabLayout.java:1272)
	at android.support.design.widget.TabLayout$TabView.performClick(TabLayout.java:1377)
	at android.view.View$PerformClick.run(View.java:21158)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Closed** 2016-11-08 21:04 UTC

**Comment by mvglasow** [comment] 2016-11-08 21:10
Think I got the culprit, turned out to be a rather stupid typo, affecting only phones on CDMA networks (which is a bit hard to test here in Europe). This will be fixed with the next release. There's one pull request that I'd like to consider for it; if I don't get to that in time, I'll make that an interim release.

Thanks for reporting and providing a logcat!

**Comment by mvglasow** [comment] 2017-06-28 14:55
Interim release 3.2 is available on F-Droid.
